"""Why this test?

To verify the complete output generated by the deployment strategy service, including deployment type, confidence score, and explanatory reason."""

from app.services.deployment_strategy import DeploymentStrategyService

service = DeploymentStrategyService()

tests = [
    ("Excellent", "Excellent"),
    ("Excellent", "Poor"),
    ("Poor", "Excellent"),
    ("Poor", "Poor"),
    ("Excellent", "Good"),
]

for solar, wind in tests:
    print({
        "solar": solar,
        "wind": wind,
        "deployment": service.recommend_deployment(solar, wind),
        "confidence": service.confidence_score(solar, wind),
        "reason": service.generate_reason(solar, wind),
    })


    #Output

    {
    "solar": "Excellent",
    "wind": "Excellent",
    "deployment": "Hybrid",
    "confidence": 95,
    "reason": "High solar irradiance and consistently strong wind resource."
}

{
    "solar": "Excellent",
    "wind": "Poor",
    "deployment": "Solar",
    "confidence": 88,
    "reason": "Strong solar resource with limited wind potential."
}

{
    "solar": "Poor",
    "wind": "Excellent",
    "deployment": "Wind",
    "confidence": 86,
    "reason": "Strong wind resource while solar potential is comparatively lower."
}

{
    "solar": "Poor",
    "wind": "Poor",
    "deployment": "Not Recommended",
    "confidence": 40,
    "reason": "Neither solar nor wind resources are sufficient for efficient deployment."
}

{
    "solar": "Excellent",
    "wind": "Good",
    "deployment": "Hybrid",
    "confidence": 91,
    "reason": "High solar irradiance and consistently strong wind resource."
}

"""
Purpose

✅ Verify the complete decision-making output."""