function MetricCard({ label, value, supporting, variant = '' }) {
  return (
    <div className={`metric-card ${variant}`}>
      <p className="metric-label">{label}</p>
      <p className="metric-value">{value}</p>
      {supporting ? <p className="metric-supporting">{supporting}</p> : null}
    </div>
  );
}

function SectionHeader({ eyebrow, title, description }) {
  return (
    <div className="dashboard-section-header">
      <div>
        {eyebrow ? <p className="dashboard-eyebrow">{eyebrow}</p> : null}
        <h2>{title}</h2>
      </div>
      {description ? <p>{description}</p> : null}
    </div>
  );
}

function ResultSection({ result, status }) {
  if (status === 'idle' || (!result && status !== 'success')) {
    return (
      <div className="card status-card">
        <div className="empty-state-icon">◎</div>
        <p className="dashboard-eyebrow">Analysis workspace</p>
        <h2>Ready for analysis</h2>
        <p>
          Enter a location, land area, and available budget to generate
          renewable deployment intelligence from the backend.
        </p>
      </div>
    );
  }

  if (!result) {
    return null;
  }

  const solar = result.solar_features || {};
  const wind = result.wind_assessment || {};
  const technical = result.technical_feasibility || {};
  const hardConstraints = technical.hard_constraints || {};
  const softConstraints = technical.soft_constraints || {};
  const energy = result.energy_yield || {};
  const financial = result.financial_metrics || {};
  const ml = result.ml_prediction || {};
  const explanation = ml.explanation || {};
  const deployment = result.deployment_plan || {};
  const recommendation = deployment.recommendation || {};
  const optimization = deployment.optimization || {};

  const topFeatures = Array.isArray(explanation.top_features)
    ? explanation.top_features
    : [];

  const feasibilityLabel =
    technical.decision ||
    (technical.is_feasible ? 'TECHNICALLY FEASIBLE' : 'NOT FEASIBLE');

  return (
    <div className="dashboard">
      {/* OVERVIEW */}
      <section className="dashboard-section overview-section">
        <SectionHeader
          eyebrow="Analysis complete"
          title="Site intelligence"
          description="Real results returned by the renewable-energy analysis pipeline."
        />

        <div className="overview-grid">
          <MetricCard
            label="Site suitability"
            value={
              result.site_suitability !== undefined
                ? `${result.site_suitability}/100`
                : 'Not available'
            }
            supporting="Overall suitability score"
            variant="featured"
          />

          <MetricCard
            label="Recommended deployment"
            value={result.recommended_deployment || 'Not available'}
            supporting={result.recommendation_reason || 'Recommendation generated by the analysis pipeline.'}
            variant="recommendation"
          />

          <MetricCard
            label="Technical feasibility"
            value={technical.is_feasible ? 'Feasible' : 'Not feasible'}
            supporting={
              technical.feasibility_score !== undefined
                ? `Feasibility score ${technical.feasibility_score}`
                : feasibilityLabel
            }
            variant={technical.is_feasible ? 'success' : 'danger'}
          />
        </div>
      </section>

      {/* RENEWABLE POTENTIAL */}
      <section className="dashboard-section">
        <SectionHeader
          eyebrow="Resource assessment"
          title="Renewable potential"
          description="Location-specific solar and wind resource indicators."
        />

        <div className="two-column-grid">
          <div className="dashboard-card">
            <div className="card-heading-row">
              <div>
                <p className="card-kicker">SOLAR</p>
                <h3>Solar resource</h3>
              </div>
              <span className="status-pill positive">Solar</span>
            </div>

            <div className="metric-list">
              <div className="detail-metric">
                <span>Solar irradiance</span>
                <strong>
                  {solar.solar_irradiance !== undefined
                    ? `${solar.solar_irradiance} kWh/m²/day`
                    : 'Not available'}
                </strong>
              </div>

              <div className="detail-metric">
                <span>Temperature</span>
                <strong>
                  {solar.temperature !== undefined
                    ? `${solar.temperature} °C`
                    : 'Not available'}
                </strong>
              </div>

              <div className="detail-metric">
                <span>Relative humidity</span>
                <strong>
                  {solar.relative_humidity !== undefined
                    ? `${solar.relative_humidity}%`
                    : 'Not available'}
                </strong>
              </div>
            </div>
          </div>

          <div className="dashboard-card">
            <div className="card-heading-row">
              <div>
                <p className="card-kicker">WIND</p>
                <h3>Wind resource</h3>
              </div>
              <span className="status-pill neutral">
                {wind.classification || 'Wind'}
              </span>
            </div>

            <div className="metric-list">
              <div className="detail-metric">
                <span>Wind speed</span>
                <strong>
                  {wind.wind_speed !== undefined
                    ? `${wind.wind_speed} m/s`
                    : 'Not available'}
                </strong>
              </div>

              <div className="detail-metric">
                <span>Classification</span>
                <strong>
                  {wind.classification || 'Not available'}
                </strong>
              </div>

              <div className="detail-metric">
                <span>Capacity factor</span>
                <strong>
                  {wind.capacity_factor !== undefined
                    ? `${wind.capacity_factor}%`
                    : 'Not available'}
                </strong>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* TECHNICAL ASSESSMENT */}
      <section className="dashboard-section">
        <SectionHeader
          eyebrow="Engineering assessment"
          title="Technical feasibility"
          description="Constraint checks and site-level technical indicators."
        />

        <div className="technical-card">
          <div className="technical-summary">
            <div className="technical-status">
              <span
                className={`status-icon ${
                  technical.is_feasible ? 'success-icon' : 'danger-icon'
                }`}
              >
                {technical.is_feasible ? '✓' : '×'}
              </span>

              <div>
                <p className="card-kicker">DECISION</p>
                <h3>{feasibilityLabel}</h3>
                <p>
                  {technical.constraint_summary ||
                    'Technical feasibility assessment completed.'}
                </p>
              </div>
            </div>

            <div className="score-block">
              <span>Feasibility score</span>
              <strong>
                {technical.feasibility_score !== undefined
                  ? technical.feasibility_score
                  : '—'}
              </strong>
            </div>
          </div>

          <div className="technical-grid">
            <div className="technical-item">
              <span>Terrain score</span>
              <strong>
                {result.terrain_score !== undefined
                  ? result.terrain_score
                  : '—'}
              </strong>
            </div>

            <div className="technical-item">
              <span>Infrastructure score</span>
              <strong>
                {result.infrastructure_score !== undefined
                  ? result.infrastructure_score
                  : '—'}
              </strong>
            </div>

            <div className="technical-item">
              <span>Hard constraints</span>
              <strong>
                {hardConstraints.passed ? 'Passed' : 'Failed'}
              </strong>
            </div>

            <div className="technical-item">
              <span>Soft constraint score</span>
              <strong>
                {softConstraints.score !== undefined
                  ? softConstraints.score
                  : '—'}
              </strong>
            </div>
          </div>
        </div>
      </section>

      {/* ENERGY + FINANCIAL */}
      <section className="dashboard-section">
        <SectionHeader
          eyebrow="Project outlook"
          title="Energy & financial analysis"
          description="Estimated generation and project-level financial indicators."
        />

        <div className="two-column-grid">
          <div className="dashboard-card">
            <div className="card-heading-row">
              <div>
                <p className="card-kicker">ENERGY</p>
                <h3>Expected generation</h3>
              </div>

              <span className="status-pill neutral">
                {energy.deployment_type || 'Analysis'}
              </span>
            </div>

            <div className="energy-total">
              <span>Total energy</span>
              <strong>
                {energy.total_energy !== undefined
                  ? `${Number(energy.total_energy).toLocaleString()}`
                  : 'Not available'}
              </strong>
              <small>Estimated annual generation</small>
            </div>

            <div className="metric-list">
              <div className="detail-metric">
                <span>Solar energy</span>
                <strong>
                  {energy.solar_energy !== undefined
                    ? Number(energy.solar_energy).toLocaleString()
                    : 'Not available'}
                </strong>
              </div>

              <div className="detail-metric">
                <span>Wind energy</span>
                <strong>
                  {energy.wind_energy !== undefined
                    ? Number(energy.wind_energy).toLocaleString()
                    : 'Not available'}
                </strong>
              </div>
            </div>
          </div>

          <div className="dashboard-card">
            <div className="card-heading-row">
              <div>
                <p className="card-kicker">FINANCIAL</p>
                <h3>Project economics</h3>
              </div>
            </div>

            <div className="financial-grid">
              <div>
                <span>Project cost</span>
                <strong>
                  {financial.estimated_project_cost !== undefined
                    ? Number(financial.estimated_project_cost).toLocaleString()
                    : 'Not available'}
                </strong>
              </div>

              <div>
                <span>Annual revenue</span>
                <strong>
                  {financial.annual_revenue !== undefined
                    ? Number(financial.annual_revenue).toLocaleString()
                    : 'Not available'}
                </strong>
              </div>

              <div>
                <span>ROI</span>
                <strong>
                  {financial.roi !== undefined
                    ? `${financial.roi}%`
                    : 'Not available'}
                </strong>
              </div>

              <div>
                <span>Payback period</span>
                <strong>
                  {financial.payback_period !== undefined
                    ? `${financial.payback_period} years`
                    : 'Not available'}
                </strong>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ML EXPLAINABILITY */}
      <section className="dashboard-section">
        <SectionHeader
          eyebrow="Machine learning"
          title="Model insight"
          description="Explainability information returned by the deployed model."
        />

        <div className="dashboard-card">
          <div className="ml-summary">
            <div>
              <p className="card-kicker">SOLAR PVOUT POTENTIAL</p>
              <strong className="ml-value">
                {ml.solar_pvout_potential !== undefined
                  ? ml.solar_pvout_potential
                  : 'Not available'}
              </strong>
            </div>

            <p className="ml-description">
              {explanation.summary ||
                'No model explanation is available for this analysis.'}
            </p>
          </div>

          {topFeatures.length > 0 ? (
            <div className="feature-list">
              <p className="card-kicker">TOP CONTRIBUTING FEATURES</p>

              {topFeatures.map((item, index) => (
                <div className="feature-row" key={`${item.feature}-${index}`}>
                  <div className="feature-name">
                    <span>{item.feature}</span>
                    <strong>
                      {item.importance !== undefined
                        ? `${(item.importance * 100).toFixed(1)}%`
                        : '—'}
                    </strong>
                  </div>

                  <div className="feature-bar">
                    <span
                      style={{
                        width: `${
                          item.importance !== undefined
                            ? Math.min(item.importance * 100, 100)
                            : 0
                        }%`,
                      }}
                    />
                  </div>
                </div>
              ))}
            </div>
          ) : null}
        </div>
      </section>

      {/* DEPLOYMENT PLAN */}
      <section className="dashboard-section">
        <SectionHeader
          eyebrow="Deployment recommendation"
          title="Recommended project strategy"
          description="Optimization and deployment planning returned by the analysis."
        />

        <div className="deployment-card">
          <div className="deployment-main">
            <div>
              <p className="card-kicker">RECOMMENDED TECHNOLOGY</p>
              <h3>
                {optimization.recommended_technology ||
                  recommendation.deployment_type ||
                  result.recommended_deployment ||
                  'Not available'}
              </h3>
              <p>
                {optimization.optimization_remarks ||
                  recommendation.reason ||
                  result.recommendation_reason ||
                  'No recommendation explanation available.'}
              </p>
            </div>

            <div className="deployment-confidence">
              <span>Confidence</span>
              <strong>
                {recommendation.confidence !== undefined
                  ? `${recommendation.confidence}`
                  : '—'}
              </strong>
            </div>
          </div>

          <div className="deployment-grid">
            <div>
              <span>Recommended capacity</span>
              <strong>
                {deployment.recommended_capacity_mw !== undefined
                  ? `${deployment.recommended_capacity_mw} MW`
                  : 'Not available'}
              </strong>
            </div>

            <div>
              <span>Priority</span>
              <strong>
                {recommendation.priority || 'Not available'}
              </strong>
            </div>

            <div>
              <span>Expansion status</span>
              <strong>
                {deployment.expansion_status || 'Not available'}
              </strong>
            </div>

            <div>
              <span>Overall score</span>
              <strong>
                {result.overall_site_score !== undefined
                  ? result.overall_site_score
                  : '—'}
              </strong>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}

export default ResultSection;